version: "3.8"

services:
  fraud_api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fraud_api
    ports:
      - "8000:8000"
    environment:
      - EXPLANATION_SERVICE_URL=http://explanation_service:8001/explain
    depends_on:
      - explanation_service
    restart: always

  explanation_service:
    build:
      context: ./explanation_service
      dockerfile: Dockerfile
    container_name: explanation_service
    ports:
      - "8001:8001"
    restart: always
